version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
  - package-ecosystem: 'npm'
    directory: '/examples/draft-0-10-0/playground'
    schedule:
      interval: monthly"
    ignore:
      - dependency-name: '*'
  - package-ecosystem: 'npm'
    directory: '/examples/draft-0-10-0/tex'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*'
  - package-ecosystem: 'npm'
    directory: '/examples/draft-0-10-0/universal'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*'
